### PR TITLE
Rest api

### PR DESCRIPTION
**Pull request by limikael**
Pull request for the functionality discussed here: https://github.com/afragen/github-updater/issues/354

Short summary:

This PR makes it possible to access a URL in a RESTful way, and as a result update a single theme or plugin. The status of the update will come back as a JSON object. The URL to access is shown on the settings page, under the "Remote Management" tab. The parameters accepted by the URL:

* `key` - The key as displayed on the "Remote Management". Must match the key stored on the
  system.
* `plugin` - Specify this to update a particular plugin. Should be specified as only the name of the
  plugin as it is known to the system, not the remote repo.
* `theme` - Specify this to update a theme.
* `tag` - Specify a particular tag, branch or commit for the update. If nothing is specified, it defaults to
  "master".
* `committish` - This is an alias for the tag parameter. I think that referring to a "committish" is more
  correct in in terms of git terminology, but it sounds a bit funny so this is why I decided to treat the
  committish and tag parameters as aliases for each other.

### CODE REVIEW

**Comment by afragen** [comment]
Thanks @limikael it will take me a while to work through this.

**Comment by afragen** [comment]
I'm going to merge this and you'll have to take me through how to test it later :wink:

I will need to change a number of things to conform to WP Coding Guidelines and this project's "guidelines", but I'll do that at the end. Most of this involves renaming the classes and spacing.

**Comment by limikael** [comment]
Awesome! I see that it is merged into the rest-api branch. What is needed for it to become "official" and released? It would be very nice for us to have it in the mainline so we can deploy it.

**Comment by afragen** [comment]
I've made a few small naming changes. Can you confirm latest `feature/rest-api` works and I'll merge into develop and then `master` at next release.

**Pull request merged**
