### PR TITLE
Update .pot and pt_PT files

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by afragen** [comment]
Pedro, I'm not quite sure I'm done making code changes that will affect the strings. Let's hold off for now. I'll update the pot when ready. Thanks for being on top of this.

**Comment by pedro-mendonca** [comment]
ok, sorry :)
:+1:

**Comment by pedro-mendonca** [comment]
@afragen 
I've synced with your .pot and now the only diffs are related to my new pt_PT.po/mo.
It's now ready to merge.

**Comment by afragen** [comment]
Thanks again Pedro.

**Pull request merged**
