### PR TITLE
Filtered options

### PR DESCRIPTION
**Pull request by teolaz1990**
filtered global options to hook and filter them using plugins

### CODE REVIEW

**Comment by afragen** [comment]
Other than being able to set the remote installation service programmatically, what's the point? The current hook provides a method to set this data. Have you tried it?

If you're looking for another way for remote management take a look at https://github.com/afragen/github-updater/wiki/Remote-Management

**Comment by teolaz1990** [comment]
These hooks are more ordered than before IMHO and allows you to filter every global option singularly, without messing up with the options array. And, they ensure you and us that if in 2 years you'll have to change $options key array, you won't have any problem as you decided options name directly on $options_names and $options_remote_names

**Comment by afragen** [comment]
Can you provide code on how this would be used?

**Comment by teolaz1990** [comment]
Of course:

on functions.php
`<?php 
   add_filter('github_updater_filter_option_bitbucket_username',function($value){
       return 'myprivateusername';
   });
?>
`

**Comment by afragen** [comment]
And this is different than

```php
add_filter( 'github_updater_token_distribution', function() {
    return array( 
                'bitbucket_username' => 'myprivateusername',
                'bitbucket_password' => 'mypassword',
                'private-theme-slug' => '1',
                 );
});
```

**Comment by teolaz1990** [comment]
Maybe you haven't read what i wrote before... please read better.

**Comment by afragen** [comment]
So a bit of historical perspective. This function has been asked for/about less than a dozen times. What you haven't told me is why the current hook is inadequate. What I see is that with this PR multiple  `add_filter` calls will be needed to set changes.

If your issue is with the naming of the filter we can discuss that using a deprecated notice.

If the wiki is unclear about what is possible, let's fix it.

**Comment by afragen** [comment]
It would be simple enough to rename the hook, see branch `deprecate-token-hook`. https://github.com/afragen/github-updater/commit/376094dc939fbd73955be09bfd4a3dab3ff6b96f

**Comment by afragen** [comment]
FYI, hook has been renamed `github_updater_set_options` https://github.com/afragen/github-updater/commit/f64cef6051a7f9f2b248035fd3bda29028e7c3fc

**Comment by teolaz1990** [comment]
Good, you've done a more descriptive hook now.
What i meant before is another thing... And just to be sure you won't do what i have in mind, i would ask you to put all the available filterable options on documentation:

GLOBAL FILTERABLE OPTIONS:
github_access_token (string)
bitbucket_username (string)
bitbucket_password (string)
gitlab_access_token (string)
gitlab_enterprise_token (string)
branch_switch (bool)

PER REPO FILTERABLE OPTIONS (could appear multiple times)
mytheme (bool|string) (where mytheme is the slug of the theme hosted remotely, bool in case of a private bitbucket repo, string in case of a github/gitlab hash)
myplugin (bool|string) (where myplugin is the slug of the plugin hosted remotely, bool in case of a private bitbucket repo, string in case of a github/gitlab hash)

This thing allow us to BE PROTECTED in case you in a remote time forget to add/remove a filter from documentation and our system starts to work badly.

**Comment by teolaz1990** [comment]
If you want, close this PR.

**Pull request closed without merging**
