### PR TITLE
Minor Improvements

### PR DESCRIPTION
**Pull request by calvintam236**

### CODE REVIEW

**Comment by afragen** [comment]
My javascript is lacking. Are you certain the PR functions correctly?

**Comment by calvintam236** [comment]
https://jsfiddle.net/4ymk1qhn/2/
Try it yourself. Basically, it is same concept.

**Comment by afragen** [comment]
Thanks!

**Comment by afragen** [comment]
I did have to tweak the javascript. Can't use jQuery shortcut as it's not defined. https://github.com/afragen/github-updater/commit/051a62d8d8894a58f501864b478970c7227a1216

**Comment by calvintam236** [comment]
It seems the jQuery in WordPress is set to NonConflict mode. Therefore,```$``` shorthand does not work. I'm not a WordPress developer either.

**Comment by afragen** [comment]
Not a big deal. The code is still an improvement. Simple fix.

**Pull request merged**
