### PR TITLE
WIP: Gitea support

### PR DESCRIPTION
**Pull request by marbetschar**
This pull request is a WIP for Gitea support in GitHub Updater. So far I've managed to recognize `Gitea Theme URI` and `Gitea Plugin URI` and also allow to set a `Gitea Access Token` in GitHub Updater settings.

@afragen Now I'm a bit lost for the next steps. What would be a good approach to develop & test `Gitea_API.php`?

### CODE REVIEW

**Comment by afragen** [comment]
Wow you've put together much of this quickly. I hope some of that's related to how modular I tried to make it :wink:

I will take a look at all this but it's going to take me some time as my day job isn't in front of my personal computer and that's what I use to code. Don't worry, we'll get there.

The best approach to test is to put up a test plugin/theme on your Gitea installation and keep looking to see if the API responses are correct. Once we actually get API correct responses back the rest should be relatively straightforward.

**Comment by marbetschar** [comment]
Awesome! It was indeed straight forward adding the extension so far - so I‘d argue the plugin is well done ;)

Nevermind, good things take some time!

I‘ll be glad if we can get this done, as we are moving from GitLab to Gitea and this is stopping us going further - on the other hand I know it takes time doing things right, so I’m not in a hurry. Just try to be as much of a help as I can :)

**Comment by marbetschar** [comment]
Any chance we can take the next step here? :)

**Comment by afragen** [comment]
Sorry, I’m still not able to give this the attention it deserves, but I will. I have made sure the `gitea` branch is currently on par with `develop`.

**Comment by marbetschar** [comment]
You merged the current Gitea WIP into `develop` right? To continue we should work in the `develop` branch?

**Comment by afragen** [comment]
It’s all in the `gitea` branch. Let’s work in there until it’s working an then merge into `develop`.

**Pull request merged**
