### PR TITLE
Update the french translation

### PR DESCRIPTION
**Pull request by benoitchantre**

### CODE REVIEW

**Comment by afragen** [comment]
Thanks @benoitchantre! Hold tight as I'm about to take a PR for using Bitbucket Stash and I'm sure there will be more strings. When it's done I'll update the POT and refer back here.

**Comment by benoitchantre** [comment]
Ok, no problem. Thanks for this plugin.

**Comment by afragen** [comment]
@benoitchantre I just updated the POT file.

**Comment by benoitchantre** [comment]
@afragen The translation is now update to date.

**Comment by afragen** [comment]
Thanks!

**Pull request merged**
