### PR TITLE
[l10n]> French update

### PR DESCRIPTION
**Pull request by fxbenard**
@daniel-menard You're welcome to have a look
@afragen good improvement

### CODE REVIEW

**Comment by daniel-menard** [comment]
Was about to PR the same!

Some suggestions :
- 91: "Hébergeur du dépôt" (seeing strings in context, it's better than what I proposed yesterday)
- 95: "Branche du dépôt"
- 99: "Dépôt BitBucket privé" (no plural)
- L196: missing ending point
- L206: missing space between %1$s and %2$s
- L233: missing space before %3$s

PS: the diff are hard to spot because there are many changes which are just different line wrapping (I had the same problem with my diff). Is there any standard on this ?

**Comment by fxbenard** [comment]
@daniel-menard let me make the changes ;) 1 less PR

**Comment by fxbenard** [comment]
@daniel-menard Done
No standard on this - It's Poedit I guess wrapping up
@afragen Ready to merge

**Comment by daniel-menard** [comment]
@fxbenard Ok, thanks!
@afragen LGTM

**Comment by afragen** [comment]
Many thanks to both of you.

**Pull request merged**
