### PR TITLE
Update Swedish translations

### PR DESCRIPTION
**Pull request by Adevade**
Update all strings in the develop branch.

### CODE REVIEW

**Comment by afragen** [comment]
@Adevade thanks for the donation and for the updates. I have to update the POT file though so you'll have to wait for this PR.

**Comment by afragen** [comment]
Andréas, you should make a new PR against the updated POT. Thanks.

**Comment by afragen** [comment]
Can you update against the new POT file? Thanks.

**Comment by Adevade** [comment]
Sorry, I've been so busy last few weeks. I'll try to get it done in the next couple of days!

**Comment by afragen** [comment]
No hurry. Thanks.

**Comment by afragen** [comment]
I just pushed an update to the POT file

**Pull request closed without merging**
