### PR TITLE
Portuguese pt_PT language files update

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by afragen** [comment]
Please update to latest .pot and check. Thanks.

I did a bunch of refactoring to set the stage for GitLab.

**Comment by pedro-mendonca** [comment]
I already updated to latest https://github.com/afragen/github-updater/commit/61d0272ea7abf479bd41c94d396e560df6a3977b. I believe this was the last commit in which you've changed the .pot strings.

**Comment by afragen** [comment]
If line numbers don't matter then all is fine. Otherwise, The line numbers in `Base.php` have changed.

**Comment by pedro-mendonca** [comment]
Yes, I've notice that and thought it won't need another PR. Still, just made another update.

**Comment by afragen** [comment]
Thanks.

**Pull request merged**
