### PR TITLE
Portuguese (pt_PT) update

### PR DESCRIPTION
**Pull request by pedro-mendonca**

### CODE REVIEW

**Comment by afragen** [comment]
There doesn't seem to be much changed.

**Comment by pedro-mendonca** [comment]
That is correct. When you added the context to that string, it got correctly taged as #fuzzy as it might need a check up. I've checked that it's correct and just took out tha #fuzzy tag that doesn't allow it to export to .mo file and to appear translated.

**Comment by afragen** [comment]
Thanks. I added the context after our last commit so others might benefit.

**Comment by pedro-mendonca** [comment]
:+1:

**Pull request merged**
